### ISSUE TITLE
How to regenerate the results in NSDI paper

### ISSUE THREAD

**Issue by goodsollee** [ushasigh/EdgeRIC-A-real-time-RIC#1]
Hi, I'm Goodsol, a graduate student in Seoul National University.

Recently, I found that this work can open chance for implementing the novel applications on RIC, so I'm trying to regenerate the results in the paper.

I make it work to execute sh file in EdgeRIC_main, but hard to know what this sh file is for and how can I use RIC with it.

If there are some detailed guidelines, I'll be pleased to follow it.

Best,
Goodsol.

**Comment by ushasigh** [comment]
I updated the repository,
Can you check this out for the code: https://github.com/ushasigh/EdgeRIC-A-real-time-RIC, 
and documentation: https://edgeric.github.io/edgeric.html. 
Once you have the network running, and traffic started, you can checkout folder /edgeric and start edgeRIC.

**Comment by goodsollee** [comment]
Thank you for your quick response! I'll try it soon and share the results.
